# Generated by Django 3.2.8 on 2021-12-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='escenariosReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipologia', models.CharField(max_length=50, verbose_name='tipologiaa')),
                ('comuna', models.IntegerField(verbose_name='comuna')),
                ('barrio', models.CharField(max_length=100, verbose_name='barrio')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
            ],
            options={
                'db_table': 'escenarios',
            },
        ),
        migrations.CreateModel(
            name='LoginUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null='True', verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=80, null='True', verbose_name='Cedula')),
                ('direccion', models.CharField(max_length=80, null='True', verbose_name='Direccion')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('clave', models.CharField(max_length=15, verbose_name='Clave')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=20, verbose_name='Fecha')),
                ('hora', models.CharField(max_length=20, verbose_name='Hora')),
                ('usuario', models.CharField(max_length=80, verbose_name='Usuario')),
                ('id_escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proSportStage.escenariosreserva')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proSportStage.loginusuarios')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
