# Generated by Django 3.2.8 on 2021-12-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proSportStage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='usuario',
        ),
    ]
