# Generated by Django 3.2.8 on 2021-12-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proSportStage', '0002_remove_reservas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusuarios',
            name='rol',
            field=models.CharField(max_length=50, null='True', verbose_name='Rol'),
            preserve_default='True',
        ),
    ]
